### ISSUE TITLE
Fine-tuning the model in 3_ft_usb_then_fib yields ValueError: Input contains NaN.

### ISSUE THREAD

**Issue by lawwu** [eugeneyan/visualizing-finetunes#1]
I'm getting an error `ValueError: Input contains NaN.` when running your notebook on a V100 in Colab. Any idea why?

<img width="801" alt="image" src="https://github.com/eugeneyan/visualizing-finetunes/assets/9869041/d5a30ec2-7576-464b-b9f0-dce67dc64f54">

**Comment by lawwu** [comment]
Looks like using the latest versions of transformers/peft caused the error, pinning to the versions you used in your library causes this to work now. Still surprised by the error though.

`%pip install -q transformers==4.35.0 accelerate bitsandbytes datasets==2.14.6 peft==0.6.0 watermark`

**Comment by eugeneyan** [comment]
I'm glad you got that fixed! I suspect it's due to the custom training code I have to reduce memory pressure during evals, as well as the custom code for evals. It should work fine without it.
